services:
  - type: web
    name: impactiq-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: NASA_API_KEY
        sync: false
      - key: WATSONX_API_KEY
        sync: false
      - key: WATSONX_PROJECT_ID
        sync: false
      - key: WATSONX_URL
        value: "https://us-south.ml.cloud.ibm.com"
